## How to create a data structure in python

In [10]:
import numpy as np 

student = np.dtype([('name','S20'), ('age', 'i1'), ('marks', 'f4')]) # This is like defining a structured data type in c
a = np.array([('kevin', 21, 50),('samay', 18, 75)], dtype = student) # Here name = kevin, age = 21 and marks = 50

print("This is the data structure for the below data",student)
print(a)
print("The name of the students in the array",a['name'])

This is the data structure for the below data [('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'kevin', 21, 50.) (b'samay', 18, 75.)]
The name of the students in the array [b'kevin' b'samay']


## Changing the dimension of an array
The below thing is about
This is about changing the dimensions of an array

In [15]:
a = np.array([[1,2,3],[4,5,6]]) 
print("This tells about the dimensions of an array",a.shape)
a.shape =(3,2)   # this is changing the number of rows and columns of an array
print(a)

This tells about the dimensions of an array (2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [23]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
print(a)
# this prints the number of dimensions in an array
print("The number of dimension in 'a' array is:",a.ndim)  

# now reshape it 
b = a.reshape(2,4,3) 
print(b) 

# this prints the number of dimensions in an array
print("The number of dimensions in 'b' array is:",b.ndim)
# b is having three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
The number of dimension in 'a' array is: 1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
The number of dimensions in 'b' array is: 3


## This is how to  create an array with zeros


In [25]:
# custom type 
import numpy as np 

# syntax is 
# numpy.ones(shape, dtype = None, order = 'C')

x = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


## This is how to create an array with ones


In [27]:
# array of five ones. Default dtype is float 
import numpy as np 
x = np.ones(5) 
print(x)

[1. 1. 1. 1. 1.]


In [28]:
x = np.ones([2,2], dtype = int) 
print(x)

[[1 1]
 [1 1]]


In [35]:
import numpy as np


## HOW  to convert string into an array

In [43]:
s = 'Hello World'

# this below line of code shows an error but this error is resolved in the below shown
# just by writing 'b' at the place of 's' and writing the string after that  
a = np.frombuffer(s, dtype = 'S1') 
print(a)

AttributeError: 'str' object has no attribute '__buffer__'

In [45]:
s = 'Hello World' 

# frombuffer is a function which converts the given string into an array the syntax is given below
# numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
a = np.frombuffer(b'hello world', dtype = 'S1') 
print(a)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


### This function builds an ndarray object from any iterable object. A new one-dimensional array is returned by this function.



In [46]:
# obtain iterator object from list 
import numpy as np 
list = range(5) 
it = iter(list)  

# use iterator to create ndarray 
# the syntax is given below
# numpy.fromiter(iterable, dtype, count = -1)

x = np.fromiter(it, dtype = float) 
print(x)

[0. 1. 2. 3. 4.]


### numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

In [47]:
# the syntax for arrage is
# numpy.arange(start, stop, step, dtype)

import numpy as np 
x = np.arange(5) 
print(x)

[0 1 2 3 4]


In [48]:
# start and stop parameters set 
import numpy as np 
x = np.arange(10,20,2) 
print(x)

[10 12 14 16 18]


### numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −



In [53]:
# numpy.linspace(start, stop, num, endpoint, retstep, dtype)

import numpy as np 

# num means its makes equal division from start point to the end point 
x = np.linspace(10,20,6) 
print(x)

[10. 12. 14. 16. 18. 20.]


### numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.



In [73]:
# numpy.logspace(start, stop, num, endpoint, base, dtype)
# endpoint : if true, stop is the last value in the range 
# base : Base of log space, default is 10

import numpy as np 
# default base is 10 

a = np.logspace(1.0, 2.0, num = 10, endpoint = True, base = 2, dtype = 'float') 
print(a)

[2.         2.16011948 2.33305808 2.5198421  2.72158    2.93946898
 3.1748021  3.42897593 3.70349885 4.        ]


## Arrange and indexing 

In [76]:
a = np.arange(10) 

# the thing in the square brackets is the index in the array
b = a[2] 
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
2


# This is how to manipulate matrix in python

In [83]:
# array to begin with 
import numpy as np 
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 

print('Our array is:')
print(a) 
print('\n')  

# this returns array of items in the second column 
print('The items in the second column are:')  
print(a[...,1]) 
print('\n')

# Now we will slice all items from the second row 
print('The items in the second row are:')
print(a[1,2])
print('\n')  

# Now we will slice all items from column 1 onwards 
print('The items column 1 onwards are:')
print(a[...,1:])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in the second column are:
[2 4 5]


The items in the second row are:
5


The items column 1 onwards are:
[[2 3]
 [4 5]
 [5 6]]
